#!/usr/bin/env bash
# configures a new Ubuntu machine with HAproxy load balancer
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sed -i '/errorfile 504/a listen thelaura' /etc/haproxy/haproxy.cfg
sed -i '/listen thelaura/a  bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a  mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a  155919-web-01 35.190.145.187:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 155919-web-01 35.190.145.187:80 check/a  server 155919-web-02 35.196.156.157:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
