#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

# Handle SIGTERM
trap "echo \"I am invincible!!!\"" 15

# print the message forever
while true;
do
    echo "To infinity and beyond";
    sleep 2
done
