#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
# Your script should only display:
#  username
#  user id
#  Home directory path for the user
i=0
while [ $i -lt 2 ]
do
    cut -d ":" -f 1,3,6 /etc/passwd
    ((i++))
done
