#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th
#  iteration, displays Best School and then Hi on a new line.
x="0"
while [ $x -lt 10 ]
do
    echo "Best School"
    if ((x == 8))
    then
        echo "Hi"
    fi
    x=$((x+1))
done
